import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

export default function Layout({ children, title }: any) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - Shop Life' : 'Shop Life'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="flex min-h-screen flex-col justify-between"
        style={{ backgroundColor: '#FFF', color: '#000' }}
      >
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/" className="text-lg font-bold">
              Shop Life
            </Link>
            <div>
              <Link href="/Cart" className="p-2">
                Cart
              </Link>
              <Link href="/Login" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          <p>Copyright © 2022 Shop Life</p>
        </footer>
      </div>
    </>
  );
}
